import { createContext, useContext, useState, type ReactNode } from 'react'

type Language = 'en' | 'kn'

interface LanguageContextValue {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LANGUAGE_STORAGE_KEY = 'workboard_language'

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar
    'home': 'Home',
    'schedules': 'Schedules',
    'personnel': 'Personnel',
    'locations': 'Locations',
    'leave_requests': 'Leave Requests',
    'reports': 'Reports',
    'audit_log': 'Audit Log',
    'settings': 'Settings',
    'configuration': 'Configuration',
    'departments': 'Departments',
    'documents': 'Documents',
    'messaging': 'Messaging',
    'shift_types': 'Shift Types',
    'shift_patterns': 'Shift Patterns',
    'rotation_rules': 'Rotation Rules',
    // Header
    'my_profile': 'My Profile',
    'help_support': 'Help & Support',
    'sign_out': 'Sign Out',
    'notifications': 'Notifications',
    'dark_mode': 'Dark mode',
    'light_mode': 'Light mode',
    // HomePage
    'welcome_back': 'Welcome back',
    'here_is_what_is_happening': 'Here is what is happening today',
    'current_cycle': 'Current Cycle',
    'todays_assignments': "Today's Assignments",
    'recent_activity': 'Recent Activity',
    'ask_anything': 'Ask anything...',
    'assistant': 'Assistant',
    'listening': 'Listening...',
    'mock_data': 'Mock Data',
    'groq_connected': 'Connected',
    'groq_fallback': 'Groq fallback to mock',
    'llama_via_groq': 'Llama 3.3 via Groq',
    'attach_file': 'Attach file',
    // Suggestions
    'sug_schedule': "Show today's schedule",
    'sug_leave': 'Who is on leave today?',
    'sug_roster': 'Generate duty roster',
    'sug_pending': 'Pending leave requests',
    // Duty types
    'guard_i': 'Guard-I',
    'guard_ii': 'Guard-II',
    'check_point': 'Check Point',
    'prison_vip_escort': 'Prison/VIP Escort',
    'striking_force': 'Striking Force',
    // Common
    'search': 'Search',
    'actions': 'Actions',
    'status': 'Status',
    'name': 'Name',
    'date': 'Date',
    'type': 'Type',
    'department': 'Department',
    'role': 'Role',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'submit': 'Submit',
    'approve': 'Approve',
    'reject': 'Reject',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'active': 'Active',
    'inactive': 'Inactive',
    'loading': 'Loading...',
    'no_data': 'No data available',
    // Schedule page
    'schedule_title': 'Schedule Management',
    'shift_assignments': 'Shift Assignments',
    'create_assignment': 'Create Assignment',
    // Employees page
    'employees_title': 'Personnel Management',
    'add_employee': 'Add Employee',
    'employee_name': 'Employee Name',
    'employee_id': 'Employee ID',
    'phone': 'Phone',
    'email': 'Email',
    // Leave page
    'leave_title': 'Leave Requests',
    'request_leave': 'Request Leave',
    'leave_type': 'Leave Type',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'reason': 'Reason',
    'annual': 'Annual',
    'sick': 'Sick',
    'personal': 'Personal',
    // Locations page
    'locations_title': 'Locations Management',
    'add_location': 'Add Location',
    'city': 'City',
    'address': 'Address',
    // Reports page
    'reports_title': 'Reports & Analytics',
    'generate_report': 'Generate Report',
    // Audit page
    'audit_title': 'Audit Log',
    'action_type': 'Action Type',
    'performed_by': 'Performed By',
    'timestamp': 'Timestamp',
    // Settings page
    'settings_title': 'Settings',
    'general': 'General',
    'appearance': 'Appearance',
    'language': 'Language',
    // Schedule page extras
    'manage_duty_rotations': 'Manage duty rotations and assignments',
    'new_assignment': 'New Assignment',
    'active_platoons': 'Active Platoons',
    'total_personnel': 'Total Personnel',
    'platoon_assignments': 'Platoon Assignments',
    'platoon': 'Platoon',
    'current_duty': 'Current Duty',
    'view_details': 'View Details',
    'overview': 'Overview',
    'timeline': 'Timeline',
    'calendar': 'Calendar',
    'cycle': 'Cycle',
    // Employees page extras
    'manage_team': 'Manage your team members and their information',
    'add_personnel': 'Add Personnel',
    'on_leave': 'On Leave',
    'training': 'Training',
    'search_name_id': 'Search by name or ID...',
    'all_ranks': 'All Ranks',
    'all_status': 'All Status',
    'section': 'Section',
    'showing': 'Showing',
    'of': 'of',
    'previous': 'Previous',
    'next': 'Next',
    'view': 'View',
    'no_personnel_found': 'No personnel found',
    // Leave page extras
    'manage_leave': 'Manage leave applications and approvals',
    'request_leave_btn': 'Request Leave',
    'remaining': 'remaining',
    'days': 'days',
    'days_used': 'days used',
    'total_requests': 'Total Requests',
    'duration': 'Duration',
    'personnel_label': 'Personnel',
    'no_leave_requests': 'No leave requests found',
    'showing_requests': 'Showing',
    'requests': 'requests',
    // Locations page extras
    'guard_duty_locations': 'Guard Duty Locations',
    'manage_locations_subtitle': 'Manage 22 guard locations across Mangaluru',
    'total_locations': 'Total Locations',
    'personnel_required': 'Personnel Required',
    'location_types': 'Location Types',
    'search_name_code': 'Search by name or code...',
    'all_types': 'All Types',
    'show_inactive': 'Show Inactive',
    'required': 'required',
    'no_locations_found': 'No locations found matching your criteria',
    'locations_by_type': 'Locations by Type',
    // Reports page extras
    'reports_subtitle': 'Karnataka State Police CAR Unit reports',
    'strength_report': 'Strength Report',
    'rotation_status': 'Rotation Status',
    'leave_utilization': 'Leave Utilization',
    'guard_duty_coverage': 'Guard Duty Coverage',
    'total_present': 'Total Present',
    'sanctioned': 'Sanctioned',
    'vacancies': 'Vacancies',
    'sections': 'Sections',
    'personnel_by_section': 'Personnel by Section',
    'personnel_by_rank': 'Personnel by Rank',
    'rank': 'Rank',
    'present': 'Present',
    'vacancy': 'Vacancy',
    'current_rotation_cycle': 'Current 15-Day Rotation Cycle',
    'rotation_schedule_next': 'Rotation Schedule (Next 3 Cycles)',
    'leave_utilization_summary': 'Leave Utilization Summary',
    'by_leave_type': 'By Leave Type',
    'quick_stats': 'Quick Stats',
    'personnel_tracked': 'Personnel Tracked',
    'total_days_entitled': 'Total Days Entitled',
    'total_days_used': 'Total Days Used',
    'guard_locations': 'Guard Locations',
    'active_locations': 'Active Locations',
    'guard_location_details': 'Guard Location Details',
    'location': 'Location',
    'code': 'Code',
    // Audit page extras
    'audit_subtitle': 'Track all system activities and changes',
    'export_log': 'Export Log',
    'total_entries': 'Total Entries',
    'creates': 'Creates',
    'updates': 'Updates',
    'deletes': 'Deletes',
    'action': 'Action',
    'entity_type': 'Entity Type',
    'entity': 'Entity',
    'details': 'Details',
    'from': 'From',
    'to': 'To',
    'user_or_entity': 'User or entity...',
    'all_actions': 'All Actions',
    'no_audit_entries': 'No audit entries found',
    'page': 'Page',
    'audit_entry_details': 'Audit Entry Details',
    'time': 'Time',
    'user': 'User',
    'before': 'Before',
    'after': 'After',
    'close': 'Close',
    // Settings page extras
    'settings_subtitle': 'Manage your account and preferences',
    'profile': 'Profile',
    'dark_mode_label': 'Dark Mode',
    'dark_mode_desc': 'Toggle between light and dark theme',
    'email_notifications': 'Email Notifications',
    'email_notifications_desc': 'Receive notifications via email',
    'schedule_changes': 'Schedule Changes',
    'swap_requests': 'Swap Requests',
    'system_alerts': 'System Alerts',
    'voice_assistant': 'Voice Assistant',
    'enable_voice': 'Enable Voice Commands',
    'enable_voice_desc': 'Use voice to interact with the chatbot',
    'data_management': 'Data Management',
    'reset_data_desc': 'Reset all application data to default seed data. This is useful for demo purposes.',
    'reset_all_data': 'Reset All Data',
    'save_settings': 'Save Settings',
    'saved': 'Saved',
    // ShiftSchedulePage
    'schedule_page_title': 'Schedule',
    'manage_team_schedules': 'Manage team schedules and shifts',
    'refresh': 'Refresh',
    'export': 'Export',
    'current_rotation': 'Current Rotation',
    'not_assigned': 'Not assigned',
    'is_not_assigned_yet': 'is not assigned yet',
    'assign_cycle': 'Assign Cycle',
    'adhoc_requests': 'Adhoc Requests',
    'assign_shift': 'Assign Shift',
    'all': 'All',
    'accepted': 'Accepted',
    'declined': 'Declined',
    'completed': 'Completed',
    'search_placeholder': 'Search...',
    'duty_type': 'Duty Type',
    'no_adhoc_requests': 'No adhoc requests found',
    'accept': 'Accept',
    'decline': 'Decline',
    'today': 'Today',
    'day': 'Day',
    'week': 'Week',
    'month': 'Month',
    'search_employees': 'Search employees by name, ID, or email...',
    'team_members': 'Team Members',
    'hours': 'Hours',
    'open_shifts': 'Open Shifts',
    'open': 'open',
    'no_employees_match': 'No employees match your filters',
    'team_members_count': 'team members',
    'shifts': 'shifts',
    'active_leaves': 'active leaves',
    'leave': 'Leave',
    'view_day': 'View Day',
    'loading_map': 'Loading map...',
    // ReportsPage
    'download_report': 'Download Report',
    'rank_distribution': 'Rank Distribution',
    'rank_breakdown': 'Rank Breakdown',
    'personnel_count_by_platoon': 'Personnel Count by Platoon',
    'leave_type_distribution': 'Leave Type Distribution',
    'leave_utilization_pct': 'Leave Utilization %',
    'used_of_entitled': 'used of {0} entitled',
    'used_slash_entitled': '{0} used / {1} entitled',
    'required_personnel_by_type': 'Required Personnel by Type',
    // MessagingConfigPage
    'messaging_configuration': 'Messaging Configuration',
    'configure_notifications': 'Configure notification templates for WhatsApp, SMS, and Email',
    'new_template': 'New Template',
    'message_templates': 'Message Templates',
    'disabled': 'Disabled',
    'test': 'Test',
    'disable': 'Disable',
    'enable': 'Enable',
    'active_templates': 'active template',
    'active_templates_plural': 'active templates',
    // MessageTemplateEditPage
    'new_message_template': 'New Message Template',
    'edit_template': 'Edit Template',
    'configure_message_content': 'Configure message content and delivery channels',
    'template_name': 'Template Name',
    'trigger_event': 'Trigger Event',
    'delivery_channels': 'Delivery Channels',
    'from_address': 'From Address / Sender',
    'message_content': 'Message Content',
    'email_subject': 'Email Subject',
    'email_body': 'Email Body',
    'whatsapp_message': 'WhatsApp Message',
    'sms_message': 'SMS Message',
    'available_variables': 'Available Variables',
    'save_as_draft': 'Save as Draft',
    'create_template': 'Create Template',
    'save_changes': 'Save Changes',
    'characters': 'characters',
    // HomePage
    'operational_pulse': 'Operational Pulse',
    'new_chat': 'New chat',
    'awaiting_command': 'Awaiting command input...',
    'staffing_rate': 'Staffing Rate',
    'section_strength': 'Section Strength',
    'operations': 'Operations',
    'guard_posts': 'Guard Posts',
    'vip_escorts': 'VIP Escorts',
    'gunmen': 'Gunmen',
    'adhoc_pending': 'Adhoc Pending',
    'vacancy_label': 'Vacancy',
    'positions': 'positions',
    'strength_overview': 'Strength Overview',
    'sanctioned_label': 'Sanctioned',
    'active_deployments': 'Active Deployments',
    'guards': 'Guards',
    'vip_escort': 'VIP Escort',
    'attention_required': 'Attention Required',
    'personnel_reported_sick': 'personnel reported sick',
    'adhoc_awaiting_approval': 'adhoc requests awaiting approval',
    'rotation_handover_48h': 'Platoon rotation handover within 48 hours',
    'current_duty_label': 'Current Duty',
    'upcoming_schedule': 'Upcoming Schedule',
    'leave_balance': 'Leave Balance',
    'next_scheduled_leave': 'Next scheduled leave',
    'none_planned': 'None planned',
    'present_label': 'present',
    'sanctioned_short': 'sanctioned',
    'staffed': 'staffed',
    // DepartmentsPage
    'manage_org_structure': 'Manage organizational structure',
    'add_department': 'Add Department',
    'edit_department': 'Edit Department',
    'department_name': 'Department Name',
    'description': 'Description',
    'parent_department': 'Parent Department',
    'none_top_level': 'None (Top Level)',
    'update': 'Update',
    'create': 'Create',
    'delete_department': 'Delete Department',
    'employees': 'Employees',
    'parent': 'Parent',
    // LocationsPage
    'search_locations': 'Search locations...',
    'no_locations_found_filters': 'No locations found matching your filters.',
    'map': 'Map',
    'list': 'List',
    'personnel_required_label': 'personnel required',
    'personnel_count': 'personnel',
    // EmployeesPage
    'id': 'ID',
    // LeaveRequestsPage
    'on_leave_today': 'On Leave Today',
    'pending_approval': 'Pending Approval',
    'all_types_leave': 'All Types',
    'no_leave_requests_found': 'No leave requests found',
    'awaiting_senior_approval': 'Awaiting senior approval',
    'period': 'Period',
    'rbac_notice': 'You can view leave requests for personnel at your rank level and below. Approval requires a senior officer.',
    // AuditPage
    'entity_type_label': 'Entity Type',
    'no_audit_entries_found': 'No audit entries found',
    // LoginPage
    'sign_in': 'Sign in',
    'signing_in': 'Signing in...',
    'sign_in_continue': 'Sign in to continue',
    'username': 'Username',
    'password': 'Password',
    'enter_username': 'Enter username',
    'enter_password': 'Enter password',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'demo_accounts': 'Demo Accounts',
    'ksp_duty_roster': 'Karnataka State Police - CAR Unit Duty Roster Management',
    'scheduling': 'Scheduling',
    // HomePage extras
    'welcome_back_comma': 'Welcome back,',
    'of_sanctioned_present': '{0} of {1} sanctioned personnel are present today',
    'pct_staffed': '{0}% staffed',
    'rotation_cycle_active': 'Rotation Cycle {0} is active',
    'next_rotation_48h': 'Next rotation in <48 hours.',
    'a_div': 'A-Div',
    'b_div': 'B-Div',
    'c_div': 'C-Div',
    'sick_label': 'sick',
    'on_leave_label': 'on leave',
    'absent_label': 'absent',
    'leave_requests_awaiting': 'leave requests awaiting approval',
    'current_duty_card': 'Current Duty',
    'upcoming_schedule_card': 'Upcoming Schedule',
    'leave_balance_card': 'Leave Balance',
    'casual_leave_cl': 'Casual Leave (CL)',
    'earned_leave_el': 'Earned Leave (EL)',
    'medical_cml': 'Medical (CML)',
    'next_scheduled_leave_label': 'Next scheduled leave',
    'none_planned_label': 'None planned',
    'guard_i_duty': 'Guard-I Duty',
    'commissioner_office': 'Commissioner Office',
    'guard_ii_rotation': 'Guard-II Rotation',
    'next_cycle': 'Next cycle',
    'district_treasury': 'District Treasury',
    'check_point_duty': 'Check Point Duty',
    'nh75_toll': 'NH-75 Toll',
    'striking_force_label': 'Striking Force',
    'cc_room': 'CC Room',
    'shift_label': 'Shift',
    'team_size': 'Team Size',
    'personnel_unit': 'personnel',
    // LeaveRequestsPage extras
    'casual_leave': 'CASUAL LEAVE',
    'medical_leave': 'MEDICAL LEAVE',
    'earned_leave': 'EARNED LEAVE',
    'privilege_leave': 'PRIVILEGE LEAVE',
    'casual_leave_full': 'Casual Leave',
    'medical_leave_full': 'Medical Leave',
    'earned_leave_full': 'Earned Leave',
    'privilege_leave_full': 'Privilege Leave',
    'of_days': 'of {0} days',
    'days_used_this_year': '{0} days used this year',
    'cancelled': 'Cancelled',
    'all_count': 'All ({0})',
    'pending_count': 'Pending ({0})',
    'approved_count': 'Approved ({0})',
    'rejected_count': 'Rejected ({0})',
    // EmployeesPage extras
    'all_label': 'All',
    'all_ranks_label': 'All Ranks',
    'all_status_label': 'All Status',
    'leadership': 'Leadership',
    // DepartmentsPage extras
    'delete_confirm_msg': 'Are you sure you want to delete "{0}"? This action cannot be undone.',
    // ShiftTypesPage
    'shift_types_title': 'Shift Types',
    'configure_shift_defs': 'Configure shift definitions',
    'add_shift_type': 'Add Shift Type',
    'edit_shift_type': 'Edit Shift Type',
    'start_time': 'Start Time',
    'end_time': 'End Time',
    'break_duration': 'Break Duration (minutes)',
    'break_label': 'Break',
    'category': 'Category',
    'color': 'Color',
    'regular': 'Regular',
    'overtime': 'Overtime',
    'on_call': 'On-Call',
    'delete_shift_type': 'Delete Shift Type',
    'delete_confirm_shift': 'Are you sure you want to delete "{0}"?',
    // ShiftPatternsPage
    'shift_patterns_title': 'Shift Patterns',
    'configure_rotation_patterns': 'Configure rotation patterns',
    'add_pattern': 'Add Pattern',
    'edit_pattern': 'Edit Pattern',
    'cycle_days': 'Cycle (days)',
    'rotation_cycle_days': 'Rotation Cycle (days)',
    // RotationRulesPage
    'rotation_rules_title': 'Rotation Rules',
    'manage_rotation_configs': 'Manage duty rotation configurations',
    'add_rule': 'Add Rule',
    'edit_rule': 'Edit Rule',
    'min_rest_hrs': 'Min Rest (hrs)',
    'max_consecutive_days': 'Max Consecutive Days',
    'priority': 'Priority',
    'min_rest_hours': 'Min Rest Hours',
    // ShiftSchedulePage extras
    'leave_legend': 'Leave',
    // Pagination
    'no_records': 'No records',
    'rows': 'Rows:',
    // ShiftTypesPage extras
    'placeholder_shift_name': 'e.g., Morning Shift',
    'placeholder_optional_desc': 'Optional description',
    'minutes_short': 'min',
    // ShiftPatternsPage extras
    'delete_pattern_confirm': 'Delete this pattern?',
    // RotationRulesPage extras
    'delete_rule_confirm': 'Delete this rule?',
    'round_robin': 'Round Robin',
    'skill_based': 'Skill Based',
    'seniority_based': 'Seniority Based',
    'preference_based': 'Preference Based',
    // LocationsPage extras
    'government_office': 'Government Office',
    'bank_currency_chest': 'Bank Currency Chest',
    'court': 'Court',
    'hospital': 'Hospital',
    'ncc': 'NCC',
    'location_subtitle': 'Mangaluru City Division — {0} active of {1} locations · {2} personnel',
    'personnel_label_suffix': 'personnel',
    // ProfilePage
    'profile_subtitle': 'View and manage your profile, leave balance, and service record',
    'tab_overview': 'Overview',
    'tab_leave_attendance': 'Leave & Attendance',
    'tab_service_record': 'Service Record',
    'tab_settings': 'Settings',
    'contact_information': 'Contact Information',
    'achievements_awards': 'Achievements & Awards',
    'used_remaining': '{0} used · {1} remaining',
    'my_pending_requests': 'My Pending Requests',
    'no_pending_leave': 'No pending leave requests',
    'holiday_calendar_2026': 'Holiday Calendar 2026',
    'service_details': 'Service Details',
    'date_of_joining': 'Date of Joining',
    'current_rank': 'Current Rank',
    'current_duty_profile': 'Current Duty',
    'unit': 'Unit',
    'district': 'District',
    'years_of_service': 'Years of Service',
    'awards_commendations': 'Awards & Commendations',
    'training_history': 'Training History',
    'account_settings': 'Account Settings',
    'sms_alerts': 'SMS Alerts',
    'sms_alerts_desc': 'Get SMS for urgent duty changes',
    'email_notif_desc': 'Receive duty and leave notifications via email',
    'language_pref_desc': 'Choose your preferred language',
    // HelpPage
    'find_answers': 'Find answers and get assistance',
    'faq_title': 'Frequently Asked Questions',
    'contact_support': 'Contact Support',
    'quick_links': 'Quick Links',
    'user_manual': 'User Manual',
    'video_tutorials': 'Video Tutorials',
    'report_issue': 'Report Issue',
    'feature_request': 'Feature Request',
    'faq_q1': 'How do I request leave?',
    'faq_a1': 'Navigate to Leave Requests from the sidebar, click "New Request", fill in the details and submit.',
    'faq_q2': 'How do I swap shifts with a colleague?',
    'faq_a2': 'Go to Swap Requests, create a new swap request by selecting the shift you want to swap and the colleague you want to swap with.',
    'faq_q3': 'How can I view my schedule?',
    'faq_a3': 'Click on Schedule in the sidebar to view your assigned shifts in calendar or list view.',
    'faq_q4': 'Who can approve my leave requests?',
    'faq_a4': 'Leave requests are approved by supervisors and administrators based on your department hierarchy.',
    'faq_q5': 'How do I update my profile information?',
    'faq_a5': 'Go to My Profile from the header dropdown and click Edit Profile to update your information.',
    // DocumentUploadPage
    'document_upload': 'Document Upload',
    'upload_parse_docs': 'Upload and parse duty documents',
    'upload_document': 'Upload Document',
    'upload_doc_desc': 'Upload policy documents, schedules, or rule files. Supported formats: PDF, DOCX, TXT, images.',
    'parsing_document': 'Parsing document...',
    'click_upload_drag': 'Click to upload or drag and drop',
    'file_types_hint': 'PDF, DOCX, TXT, or images up to 10MB',
    'overall_confidence': 'Overall Confidence',
    'extracted_rules': 'Extracted Rules',
    'upload_history': 'Upload History',
    'rules_extracted': '{0} rules extracted',
    'create_rotation_rules_btn': 'Create {0} Rotation Rule(s)',
    // Sidebar extras
    'admin_section': 'ADMIN',
    'expand': 'Expand',
    'collapse_sidebar': 'Collapse',
    // LocationsPage CRUD
    'add_location_btn': 'Add Location',
    'edit_location': 'Edit Location',
    'delete_location': 'Delete Location',
    'delete_location_confirm': 'Are you sure you want to delete "{0}"?',
    'location_name': 'Location Name',
    'location_code': 'Location Code',
    'location_type': 'Location Type',
    'required_personnel_field': 'Required Personnel',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'other': 'Other',
    'location_created': 'Location created successfully',
    'location_updated': 'Location updated successfully',
    'location_deleted': 'Location deleted successfully',
    'all_locations': 'All Locations',
    'back_to_locations': 'Back to Locations',
    'configure_location_details': 'Configure location details and map position',
    'click_map_to_pick': 'Click on the map to pick coordinates',
    'click_map_pick': 'Click on the map or drag the marker to pick coordinates',
    'map_preview': 'Map Preview',
    'preset_type': 'Preset',
    'custom_type': 'Custom',
    'enter_custom_type': 'Enter custom location type...',
  },
  kn: {
    // Sidebar
    'home': 'ಮುಖಪುಟ',
    'schedules': 'ವೇಳಾಪಟ್ಟಿಗಳು',
    'personnel': 'ಸಿಬ್ಬಂದಿ',
    'locations': 'ಸ್ಥಳಗಳು',
    'leave_requests': 'ರಜೆ ವಿನಂತಿಗಳು',
    'reports': 'ವರದಿಗಳು',
    'audit_log': 'ಆಡಿಟ್ ಲಾಗ್',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'configuration': 'ಸಂರಚನೆ',
    'departments': 'ವಿಭಾಗಗಳು',
    'documents': 'ದಾಖಲೆಗಳು',
    'messaging': 'ಸಂದೇಶ',
    'shift_types': 'ಶಿಫ್ಟ್ ವಿಧಗಳು',
    'shift_patterns': 'ಶಿಫ್ಟ್ ಮಾದರಿಗಳು',
    'rotation_rules': 'ತಿರುಗುವಿಕೆ ನಿಯಮಗಳು',
    // Header
    'my_profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    'sign_out': 'ಸೈನ್ ಔಟ್',
    'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'light_mode': 'ಲೈಟ್ ಮೋಡ್',
    // HomePage
    'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ',
    'here_is_what_is_happening': 'ಇಂದು ಏನಾಗುತ್ತಿದೆ ಎಂಬುದು ಇಲ್ಲಿದೆ',
    'current_cycle': 'ಪ್ರಸ್ತುತ ಚಕ್ರ',
    'todays_assignments': 'ಇಂದಿನ ನಿಯೋಜನೆಗಳು',
    'recent_activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    'ask_anything': 'ಏನಾದರೂ ಕೇಳಿ...',
    'assistant': 'ಸಹಾಯಕ',
    'listening': 'ಆಲಿಸುತ್ತಿದೆ...',
    'mock_data': 'ಮಾಕ್ ಡೇಟಾ',
    'groq_connected': 'ಸಂಪರ್ಕಿತ',
    'groq_fallback': 'Groq ಮಾಕ್‌ಗೆ ಫಾಲ್‌ಬ್ಯಾಕ್',
    'llama_via_groq': 'Llama 3.3 Groq ಮೂಲಕ',
    'attach_file': 'ಫೈಲ್ ಲಗತ್ತಿಸಿ',
    // Suggestions
    'sug_schedule': 'ಇಂದಿನ ವೇಳಾಪಟ್ಟಿ ತೋರಿಸಿ',
    'sug_leave': 'ಇಂದು ಯಾರು ರಜೆಯಲ್ಲಿದ್ದಾರೆ?',
    'sug_roster': 'ಕರ್ತವ್ಯ ರೋಸ್ಟರ್ ರಚಿಸಿ',
    'sug_pending': 'ಬಾಕಿ ರಜೆ ವಿನಂತಿಗಳು',
    // Duty types
    'guard_i': 'ಗಾರ್ಡ್-I',
    'guard_ii': 'ಗಾರ್ಡ್-II',
    'check_point': 'ಚೆಕ್ ಪಾಯಿಂಟ್',
    'prison_vip_escort': 'ಜೈಲು/ವಿಐಪಿ ಎಸ್ಕಾರ್ಟ್',
    'striking_force': 'ಸ್ಟ್ರೈಕಿಂಗ್ ಫೋರ್ಸ್',
    // Common
    'search': 'ಹುಡುಕಿ',
    'actions': 'ಕ್ರಿಯೆಗಳು',
    'status': 'ಸ್ಥಿತಿ',
    'name': 'ಹೆಸರು',
    'date': 'ದಿನಾಂಕ',
    'type': 'ಪ್ರಕಾರ',
    'department': 'ಇಲಾಖೆ',
    'role': 'ಪಾತ್ರ',
    'save': 'ಉಳಿಸಿ',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'delete': 'ಅಳಿಸಿ',
    'edit': 'ಸಂಪಾದಿಸಿ',
    'add': 'ಸೇರಿಸಿ',
    'submit': 'ಸಲ್ಲಿಸಿ',
    'approve': 'ಅನುಮೋದಿಸಿ',
    'reject': 'ತಿರಸ್ಕರಿಸಿ',
    'pending': 'ಬಾಕಿ',
    'approved': 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    'rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    'active': 'ಸಕ್ರಿಯ',
    'inactive': 'ನಿಷ್ಕ್ರಿಯ',
    'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'no_data': 'ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ',
    // Schedule page
    'schedule_title': 'ವೇಳಾಪಟ್ಟಿ ನಿರ್ವಹಣೆ',
    'shift_assignments': 'ಶಿಫ್ಟ್ ನಿಯೋಜನೆಗಳು',
    'create_assignment': 'ನಿಯೋಜನೆ ರಚಿಸಿ',
    // Employees page
    'employees_title': 'ಸಿಬ್ಬಂದಿ ನಿರ್ವಹಣೆ',
    'add_employee': 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ',
    'employee_name': 'ಸಿಬ್ಬಂದಿ ಹೆಸರು',
    'employee_id': 'ಸಿಬ್ಬಂದಿ ಐಡಿ',
    'phone': 'ಫೋನ್',
    'email': 'ಇಮೇಲ್',
    // Leave page
    'leave_title': 'ರಜೆ ವಿನಂತಿಗಳು',
    'request_leave': 'ರಜೆ ವಿನಂತಿಸಿ',
    'leave_type': 'ರಜೆ ಪ್ರಕಾರ',
    'start_date': 'ಪ್ರಾರಂಭ ದಿನಾಂಕ',
    'end_date': 'ಅಂತಿಮ ದಿನಾಂಕ',
    'reason': 'ಕಾರಣ',
    'annual': 'ವಾರ್ಷಿಕ',
    'sick': 'ಅನಾರೋಗ್ಯ',
    'personal': 'ವೈಯಕ್ತಿಕ',
    // Locations page
    'locations_title': 'ಸ್ಥಳಗಳ ನಿರ್ವಹಣೆ',
    'add_location': 'ಸ್ಥಳ ಸೇರಿಸಿ',
    'city': 'ನಗರ',
    'address': 'ವಿಳಾಸ',
    // Reports page
    'reports_title': 'ವರದಿಗಳು ಮತ್ತು ವಿಶ್ಲೇಷಣೆ',
    'generate_report': 'ವರದಿ ರಚಿಸಿ',
    // Audit page
    'audit_title': 'ಆಡಿಟ್ ಲಾಗ್',
    'action_type': 'ಕ್ರಿಯೆ ಪ್ರಕಾರ',
    'performed_by': 'ನಿರ್ವಹಿಸಿದವರು',
    'timestamp': 'ಸಮಯ ಮುದ್ರೆ',
    // Settings page
    'settings_title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'general': 'ಸಾಮಾನ್ಯ',
    'appearance': 'ನೋಟ',
    'language': 'ಭಾಷೆ',
    // Schedule page extras
    'manage_duty_rotations': 'ಕರ್ತವ್ಯ ಸರದಿಗಳು ಮತ್ತು ನಿಯೋಜನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'new_assignment': 'ಹೊಸ ನಿಯೋಜನೆ',
    'active_platoons': 'ಸಕ್ರಿಯ ಪ್ಲಟೂನ್‌ಗಳು',
    'total_personnel': 'ಒಟ್ಟು ಸಿಬ್ಬಂದಿ',
    'platoon_assignments': 'ಪ್ಲಟೂನ್ ನಿಯೋಜನೆಗಳು',
    'platoon': 'ಪ್ಲಟೂನ್',
    'current_duty': 'ಪ್ರಸ್ತುತ ಕರ್ತವ್ಯ',
    'view_details': 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    'overview': 'ಅವಲೋಕನ',
    'timeline': 'ಸಮಯರೇಖೆ',
    'calendar': 'ಕ್ಯಾಲೆಂಡರ್',
    'cycle': 'ಚಕ್ರ',
    // Employees page extras
    'manage_team': 'ನಿಮ್ಮ ತಂಡದ ಸದಸ್ಯರು ಮತ್ತು ಅವರ ಮಾಹಿತಿಯನ್ನು ನಿರ್ವಹಿಸಿ',
    'add_personnel': 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ',
    'on_leave': 'ರಜೆಯಲ್ಲಿ',
    'training': 'ತರಬೇತಿ',
    'search_name_id': 'ಹೆಸರು ಅಥವಾ ಐಡಿ ಮೂಲಕ ಹುಡುಕಿ...',
    'all_ranks': 'ಎಲ್ಲಾ ಶ್ರೇಣಿಗಳು',
    'all_status': 'ಎಲ್ಲಾ ಸ್ಥಿತಿ',
    'section': 'ವಿಭಾಗ',
    'showing': 'ತೋರಿಸುತ್ತಿದೆ',
    'of': 'ರಲ್ಲಿ',
    'previous': 'ಹಿಂದಿನ',
    'next': 'ಮುಂದಿನ',
    'view': 'ನೋಡಿ',
    'no_personnel_found': 'ಸಿಬ್ಬಂದಿ ಕಂಡುಬಂದಿಲ್ಲ',
    // Leave page extras
    'manage_leave': 'ರಜೆ ಅರ್ಜಿಗಳು ಮತ್ತು ಅನುಮೋದನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'request_leave_btn': 'ರಜೆ ವಿನಂತಿಸಿ',
    'remaining': 'ಉಳಿದಿದೆ',
    'days': 'ದಿನಗಳು',
    'days_used': 'ದಿನಗಳು ಬಳಸಲಾಗಿದೆ',
    'total_requests': 'ಒಟ್ಟು ವಿನಂತಿಗಳು',
    'duration': 'ಅವಧಿ',
    'personnel_label': 'ಸಿಬ್ಬಂದಿ',
    'no_leave_requests': 'ರಜೆ ವಿನಂತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'showing_requests': 'ತೋರಿಸುತ್ತಿದೆ',
    'requests': 'ವಿನಂತಿಗಳು',
    // Locations page extras
    'guard_duty_locations': 'ಕಾವಲು ಕರ್ತವ್ಯ ಸ್ಥಳಗಳು',
    'manage_locations_subtitle': 'ಮಂಗಳೂರಿನಾದ್ಯಂತ 22 ಕಾವಲು ಸ್ಥಳಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'total_locations': 'ಒಟ್ಟು ಸ್ಥಳಗಳು',
    'personnel_required': 'ಅಗತ್ಯ ಸಿಬ್ಬಂದಿ',
    'location_types': 'ಸ್ಥಳ ಪ್ರಕಾರಗಳು',
    'search_name_code': 'ಹೆಸರು ಅಥವಾ ಕೋಡ್ ಮೂಲಕ ಹುಡುಕಿ...',
    'all_types': 'ಎಲ್ಲಾ ಪ್ರಕಾರಗಳು',
    'show_inactive': 'ನಿಷ್ಕ್ರಿಯ ತೋರಿಸಿ',
    'required': 'ಅಗತ್ಯ',
    'no_locations_found': 'ನಿಮ್ಮ ಮಾನದಂಡಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುವ ಸ್ಥಳಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'locations_by_type': 'ಪ್ರಕಾರದ ಪ್ರಕಾರ ಸ್ಥಳಗಳು',
    // Reports page extras
    'reports_subtitle': 'ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್ CAR ಘಟಕ ವರದಿಗಳು',
    'strength_report': 'ಬಲ ವರದಿ',
    'rotation_status': 'ಸರದಿ ಸ್ಥಿತಿ',
    'leave_utilization': 'ರಜೆ ಬಳಕೆ',
    'guard_duty_coverage': 'ಕಾವಲು ಕರ್ತವ್ಯ ವ್ಯಾಪ್ತಿ',
    'total_present': 'ಒಟ್ಟು ಹಾಜರು',
    'sanctioned': 'ಮಂಜೂರಾದ',
    'vacancies': 'ಖಾಲಿ ಹುದ್ದೆಗಳು',
    'sections': 'ವಿಭಾಗಗಳು',
    'personnel_by_section': 'ವಿಭಾಗದ ಪ್ರಕಾರ ಸಿಬ್ಬಂದಿ',
    'personnel_by_rank': 'ಶ್ರೇಣಿಯ ಪ್ರಕಾರ ಸಿಬ್ಬಂದಿ',
    'rank': 'ಶ್ರೇಣಿ',
    'present': 'ಹಾಜರು',
    'vacancy': 'ಖಾಲಿ ಹುದ್ದೆ',
    'current_rotation_cycle': 'ಪ್ರಸ್ತುತ 15-ದಿನ ಸರದಿ ಚಕ್ರ',
    'rotation_schedule_next': 'ಸರದಿ ವೇಳಾಪಟ್ಟಿ (ಮುಂದಿನ 3 ಚಕ್ರಗಳು)',
    'leave_utilization_summary': 'ರಜೆ ಬಳಕೆ ಸಾರಾಂಶ',
    'by_leave_type': 'ರಜೆ ಪ್ರಕಾರದ ಪ್ರಕಾರ',
    'quick_stats': 'ತ್ವರಿತ ಅಂಕಿಅಂಶಗಳು',
    'personnel_tracked': 'ಟ್ರ್ಯಾಕ್ ಮಾಡಿದ ಸಿಬ್ಬಂದಿ',
    'total_days_entitled': 'ಒಟ್ಟು ಅರ್ಹ ದಿನಗಳು',
    'total_days_used': 'ಒಟ್ಟು ಬಳಸಿದ ದಿನಗಳು',
    'guard_locations': 'ಕಾವಲು ಸ್ಥಳಗಳು',
    'active_locations': 'ಸಕ್ರಿಯ ಸ್ಥಳಗಳು',
    'guard_location_details': 'ಕಾವಲು ಸ್ಥಳ ವಿವರಗಳು',
    'location': 'ಸ್ಥಳ',
    'code': 'ಕೋಡ್',
    // Audit page extras
    'audit_subtitle': 'ಎಲ್ಲಾ ಸಿಸ್ಟಮ್ ಚಟುವಟಿಕೆಗಳು ಮತ್ತು ಬದಲಾವಣೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'export_log': 'ಲಾಗ್ ರಫ್ತು ಮಾಡಿ',
    'total_entries': 'ಒಟ್ಟು ನಮೂದುಗಳು',
    'creates': 'ರಚನೆಗಳು',
    'updates': 'ನವೀಕರಣಗಳು',
    'deletes': 'ಅಳಿಸುವಿಕೆಗಳು',
    'action': 'ಕ್ರಿಯೆ',
    'entity_type': 'ಘಟಕ ಪ್ರಕಾರ',
    'entity': 'ಘಟಕ',
    'details': 'ವಿವರಗಳು',
    'from': 'ಇಂದ',
    'to': 'ವರೆಗೆ',
    'user_or_entity': 'ಬಳಕೆದಾರ ಅಥವಾ ಘಟಕ...',
    'all_actions': 'ಎಲ್ಲಾ ಕ್ರಿಯೆಗಳು',
    'no_audit_entries': 'ಆಡಿಟ್ ನಮೂದುಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'page': 'ಪುಟ',
    'audit_entry_details': 'ಆಡಿಟ್ ನಮೂದು ವಿವರಗಳು',
    'time': 'ಸಮಯ',
    'user': 'ಬಳಕೆದಾರ',
    'before': 'ಮೊದಲು',
    'after': 'ನಂತರ',
    'close': 'ಮುಚ್ಚಿ',
    // Settings page extras
    'settings_subtitle': 'ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'dark_mode_label': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'dark_mode_desc': 'ಲೈಟ್ ಮತ್ತು ಡಾರ್ಕ್ ಥೀಮ್ ನಡುವೆ ಬದಲಿಸಿ',
    'email_notifications': 'ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳು',
    'email_notifications_desc': 'ಇಮೇಲ್ ಮೂಲಕ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    'schedule_changes': 'ವೇಳಾಪಟ್ಟಿ ಬದಲಾವಣೆಗಳು',
    'swap_requests': 'ವಿನಿಮಯ ವಿನಂತಿಗಳು',
    'system_alerts': 'ಸಿಸ್ಟಮ್ ಎಚ್ಚರಿಕೆಗಳು',
    'voice_assistant': 'ಧ್ವನಿ ಸಹಾಯಕ',
    'enable_voice': 'ಧ್ವನಿ ಆಜ್ಞೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'enable_voice_desc': 'ಚಾಟ್‌ಬಾಟ್‌ನೊಂದಿಗೆ ಸಂವಹನ ನಡೆಸಲು ಧ್ವನಿ ಬಳಸಿ',
    'data_management': 'ಡೇಟಾ ನಿರ್ವಹಣೆ',
    'reset_data_desc': 'ಎಲ್ಲಾ ಅಪ್ಲಿಕೇಶನ್ ಡೇಟಾವನ್ನು ಡೀಫಾಲ್ಟ್ ಸೀಡ್ ಡೇಟಾಗೆ ಮರುಹೊಂದಿಸಿ. ಇದು ಡೆಮೊ ಉದ್ದೇಶಗಳಿಗೆ ಉಪಯುಕ್ತ.',
    'reset_all_data': 'ಎಲ್ಲಾ ಡೇಟಾ ಮರುಹೊಂದಿಸಿ',
    'save_settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ',
    'saved': 'ಉಳಿಸಲಾಗಿದೆ',
    // ShiftSchedulePage
    'schedule_page_title': 'ವೇಳಾಪಟ್ಟಿ',
    'manage_team_schedules': 'ತಂಡದ ವೇಳಾಪಟ್ಟಿಗಳು ಮತ್ತು ಶಿಫ್ಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'refresh': 'ರಿಫ್ರೆಶ್',
    'export': 'ರಫ್ತು',
    'current_rotation': 'ಪ್ರಸ್ತುತ ಸರದಿ',
    'not_assigned': 'ನಿಯೋಜಿಸಲಾಗಿಲ್ಲ',
    'is_not_assigned_yet': 'ಇನ್ನೂ ನಿಯೋಜಿಸಲಾಗಿಲ್ಲ',
    'assign_cycle': 'ಚಕ್ರ ನಿಯೋಜಿಸಿ',
    'adhoc_requests': 'ಅಡ್‌ಹಾಕ್ ವಿನಂತಿಗಳು',
    'assign_shift': 'ಶಿಫ್ಟ್ ನಿಯೋಜಿಸಿ',
    'all': 'ಎಲ್ಲಾ',
    'accepted': 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    'declined': 'ನಿರಾಕರಿಸಲಾಗಿದೆ',
    'completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'search_placeholder': 'ಹುಡುಕಿ...',
    'duty_type': 'ಕರ್ತವ್ಯ ಪ್ರಕಾರ',
    'no_adhoc_requests': 'ಅಡ್‌ಹಾಕ್ ವಿನಂತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'accept': 'ಸ್ವೀಕರಿಸಿ',
    'decline': 'ನಿರಾಕರಿಸಿ',
    'today': 'ಇಂದು',
    'day': 'ದಿನ',
    'week': 'ವಾರ',
    'month': 'ತಿಂಗಳು',
    'search_employees': 'ಹೆಸರು, ಐಡಿ ಅಥವಾ ಇಮೇಲ್ ಮೂಲಕ ಸಿಬ್ಬಂದಿ ಹುಡುಕಿ...',
    'team_members': 'ತಂಡದ ಸದಸ್ಯರು',
    'hours': 'ಗಂಟೆಗಳು',
    'open_shifts': 'ತೆರೆದ ಶಿಫ್ಟ್‌ಗಳು',
    'open': 'ತೆರೆದ',
    'no_employees_match': 'ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಸಿಬ್ಬಂದಿ ಇಲ್ಲ',
    'team_members_count': 'ತಂಡದ ಸದಸ್ಯರು',
    'shifts': 'ಶಿಫ್ಟ್‌ಗಳು',
    'active_leaves': 'ಸಕ್ರಿಯ ರಜೆಗಳು',
    'leave': 'ರಜೆ',
    'view_day': 'ದಿನ ನೋಡಿ',
    'loading_map': 'ನಕ್ಷೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    // ReportsPage
    'download_report': 'ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    'rank_distribution': 'ಶ್ರೇಣಿ ವಿತರಣೆ',
    'rank_breakdown': 'ಶ್ರೇಣಿ ವಿಭಜನೆ',
    'personnel_count_by_platoon': 'ಪ್ಲಟೂನ್ ಪ್ರಕಾರ ಸಿಬ್ಬಂದಿ ಸಂಖ್ಯೆ',
    'leave_type_distribution': 'ರಜೆ ಪ್ರಕಾರ ವಿತರಣೆ',
    'leave_utilization_pct': 'ರಜೆ ಬಳಕೆ %',
    'used_of_entitled': '{0} ಅರ್ಹತೆಯಲ್ಲಿ ಬಳಸಲಾಗಿದೆ',
    'used_slash_entitled': '{0} ಬಳಸಲಾಗಿದೆ / {1} ಅರ್ಹ',
    'required_personnel_by_type': 'ಪ್ರಕಾರದ ಪ್ರಕಾರ ಅಗತ್ಯ ಸಿಬ್ಬಂದಿ',
    // MessagingConfigPage
    'messaging_configuration': 'ಸಂದೇಶ ಸಂರಚನೆ',
    'configure_notifications': 'WhatsApp, SMS ಮತ್ತು ಇಮೇಲ್‌ಗಾಗಿ ಅಧಿಸೂಚನೆ ಟೆಂಪ್ಲೇಟ್‌ಗಳನ್ನು ಸಂರಚಿಸಿ',
    'new_template': 'ಹೊಸ ಟೆಂಪ್ಲೇಟ್',
    'message_templates': 'ಸಂದೇಶ ಟೆಂಪ್ಲೇಟ್‌ಗಳು',
    'disabled': 'ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ',
    'test': 'ಪರೀಕ್ಷೆ',
    'disable': 'ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
    'enable': 'ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'active_templates': 'ಸಕ್ರಿಯ ಟೆಂಪ್ಲೇಟ್',
    'active_templates_plural': 'ಸಕ್ರಿಯ ಟೆಂಪ್ಲೇಟ್‌ಗಳು',
    // MessageTemplateEditPage
    'new_message_template': 'ಹೊಸ ಸಂದೇಶ ಟೆಂಪ್ಲೇಟ್',
    'edit_template': 'ಟೆಂಪ್ಲೇಟ್ ಸಂಪಾದಿಸಿ',
    'configure_message_content': 'ಸಂದೇಶ ವಿಷಯ ಮತ್ತು ವಿತರಣಾ ಚಾನೆಲ್‌ಗಳನ್ನು ಸಂರಚಿಸಿ',
    'template_name': 'ಟೆಂಪ್ಲೇಟ್ ಹೆಸರು',
    'trigger_event': 'ಟ್ರಿಗರ್ ಈವೆಂಟ್',
    'delivery_channels': 'ವಿತರಣಾ ಚಾನೆಲ್‌ಗಳು',
    'from_address': 'ಕಳುಹಿಸುವವರ ವಿಳಾಸ',
    'message_content': 'ಸಂದೇಶ ವಿಷಯ',
    'email_subject': 'ಇಮೇಲ್ ವಿಷಯ',
    'email_body': 'ಇಮೇಲ್ ಮುಖ್ಯಭಾಗ',
    'whatsapp_message': 'WhatsApp ಸಂದೇಶ',
    'sms_message': 'SMS ಸಂದೇಶ',
    'available_variables': 'ಲಭ್ಯವಿರುವ ವೇರಿಯಬಲ್‌ಗಳು',
    'save_as_draft': 'ಡ್ರಾಫ್ಟ್ ಆಗಿ ಉಳಿಸಿ',
    'create_template': 'ಟೆಂಪ್ಲೇಟ್ ರಚಿಸಿ',
    'save_changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    'characters': 'ಅಕ್ಷರಗಳು',
    // HomePage
    'operational_pulse': 'ಕಾರ್ಯಾಚರಣೆ ನಾಡಿ',
    'new_chat': 'ಹೊಸ ಚಾಟ್',
    'awaiting_command': 'ಆಜ್ಞೆ ಇನ್‌ಪುಟ್‌ಗಾಗಿ ಕಾಯುತ್ತಿದೆ...',
    'staffing_rate': 'ಸಿಬ್ಬಂದಿ ದರ',
    'section_strength': 'ವಿಭಾಗ ಬಲ',
    'operations': 'ಕಾರ್ಯಾಚರಣೆಗಳು',
    'guard_posts': 'ಕಾವಲು ಕೇಂದ್ರಗಳು',
    'vip_escorts': 'ವಿಐಪಿ ಎಸ್ಕಾರ್ಟ್‌ಗಳು',
    'gunmen': 'ಗನ್‌ಮೆನ್',
    'adhoc_pending': 'ಅಡ್‌ಹಾಕ್ ಬಾಕಿ',
    'vacancy_label': 'ಖಾಲಿ ಹುದ್ದೆ',
    'positions': 'ಹುದ್ದೆಗಳು',
    'strength_overview': 'ಬಲ ಅವಲೋಕನ',
    'sanctioned_label': 'ಮಂಜೂರಾದ',
    'active_deployments': 'ಸಕ್ರಿಯ ನಿಯೋಜನೆಗಳು',
    'guards': 'ಕಾವಲುಗಾರರು',
    'vip_escort': 'ವಿಐಪಿ ಎಸ್ಕಾರ್ಟ್',
    'attention_required': 'ಗಮನ ಅಗತ್ಯ',
    'personnel_reported_sick': 'ಸಿಬ್ಬಂದಿ ಅನಾರೋಗ್ಯ ವರದಿ ಮಾಡಿದ್ದಾರೆ',
    'adhoc_awaiting_approval': 'ಅಡ್‌ಹಾಕ್ ವಿನಂತಿಗಳು ಅನುಮೋದನೆಗಾಗಿ ಕಾಯುತ್ತಿವೆ',
    'rotation_handover_48h': '48 ಗಂಟೆಗಳಲ್ಲಿ ಪ್ಲಟೂನ್ ಸರದಿ ಹಸ್ತಾಂತರ',
    'current_duty_label': 'ಪ್ರಸ್ತುತ ಕರ್ತವ್ಯ',
    'upcoming_schedule': 'ಮುಂಬರುವ ವೇಳಾಪಟ್ಟಿ',
    'leave_balance': 'ರಜೆ ಬಾಕಿ',
    'next_scheduled_leave': 'ಮುಂದಿನ ನಿಗದಿತ ರಜೆ',
    'none_planned': 'ಯೋಜಿಸಲಾಗಿಲ್ಲ',
    'present_label': 'ಹಾಜರು',
    'sanctioned_short': 'ಮಂಜೂರಾದ',
    'staffed': 'ಸಿಬ್ಬಂದಿ ಹೊಂದಿದೆ',
    // DepartmentsPage
    'manage_org_structure': 'ಸಾಂಸ್ಥಿಕ ರಚನೆಯನ್ನು ನಿರ್ವಹಿಸಿ',
    'add_department': 'ವಿಭಾಗ ಸೇರಿಸಿ',
    'edit_department': 'ವಿಭಾಗ ಸಂಪಾದಿಸಿ',
    'department_name': 'ವಿಭಾಗದ ಹೆಸರು',
    'description': 'ವಿವರಣೆ',
    'parent_department': 'ಮೂಲ ವಿಭಾಗ',
    'none_top_level': 'ಯಾವುದೂ ಇಲ್ಲ (ಉನ್ನತ ಮಟ್ಟ)',
    'update': 'ನವೀಕರಿಸಿ',
    'create': 'ರಚಿಸಿ',
    'delete_department': 'ವಿಭಾಗ ಅಳಿಸಿ',
    'employees': 'ಉದ್ಯೋಗಿಗಳು',
    'parent': 'ಮೂಲ',
    // LocationsPage
    'search_locations': 'ಸ್ಥಳಗಳನ್ನು ಹುಡುಕಿ...',
    'no_locations_found_filters': 'ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಸ್ಥಳಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    'map': 'ನಕ್ಷೆ',
    'list': 'ಪಟ್ಟಿ',
    'personnel_required_label': 'ಅಗತ್ಯ ಸಿಬ್ಬಂದಿ',
    'personnel_count': 'ಸಿಬ್ಬಂದಿ',
    // EmployeesPage
    'id': 'ಐಡಿ',
    // LeaveRequestsPage
    'on_leave_today': 'ಇಂದು ರಜೆಯಲ್ಲಿ',
    'pending_approval': 'ಅನುಮೋದನೆ ಬಾಕಿ',
    'all_types_leave': 'ಎಲ್ಲಾ ಪ್ರಕಾರಗಳು',
    'no_leave_requests_found': 'ರಜೆ ವಿನಂತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'awaiting_senior_approval': 'ಹಿರಿಯ ಅಧಿಕಾರಿಯ ಅನುಮೋದನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
    'period': 'ಅವಧಿ',
    'rbac_notice': 'ನಿಮ್ಮ ಶ್ರೇಣಿ ಮಟ್ಟ ಮತ್ತು ಕೆಳಗಿನ ಸಿಬ್ಬಂದಿಯ ರಜೆ ವಿನಂತಿಗಳನ್ನು ನೀವು ನೋಡಬಹುದು. ಅನುಮೋದನೆಗೆ ಹಿರಿಯ ಅಧಿಕಾರಿ ಅಗತ್ಯ.',
    // AuditPage
    'entity_type_label': 'ಘಟಕ ಪ್ರಕಾರ',
    'no_audit_entries_found': 'ಆಡಿಟ್ ನಮೂದುಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    // LoginPage
    'sign_in': 'ಸೈನ್ ಇನ್',
    'signing_in': 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    'sign_in_continue': 'ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'username': 'ಬಳಕೆದಾರ ಹೆಸರು',
    'password': 'ಪಾಸ್‌ವರ್ಡ್',
    'enter_username': 'ಬಳಕೆದಾರ ಹೆಸರು ನಮೂದಿಸಿ',
    'enter_password': 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'remember_me': 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    'forgot_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    'demo_accounts': 'ಡೆಮೊ ಖಾತೆಗಳು',
    'ksp_duty_roster': 'ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್ - CAR ಘಟಕ ಕರ್ತವ್ಯ ರೋಸ್ಟರ್ ನಿರ್ವಹಣೆ',
    'scheduling': 'ವೇಳಾಪಟ್ಟಿ',
    // HomePage extras
    'welcome_back_comma': 'ಮರಳಿ ಸ್ವಾಗತ,',
    'of_sanctioned_present': '{0} ರಲ್ಲಿ {1} ಮಂಜೂರಾದ ಸಿಬ್ಬಂದಿ ಇಂದು ಹಾಜರಿದ್ದಾರೆ',
    'pct_staffed': '{0}% ಸಿಬ್ಬಂದಿ ಹೊಂದಿದೆ',
    'rotation_cycle_active': 'ಸರದಿ ಚಕ್ರ {0} ಸಕ್ರಿಯವಾಗಿದೆ',
    'next_rotation_48h': 'ಮುಂದಿನ ಸರದಿ <48 ಗಂಟೆಗಳಲ್ಲಿ.',
    'a_div': 'ಎ-ವಿಭಾಗ',
    'b_div': 'ಬಿ-ವಿಭಾಗ',
    'c_div': 'ಸಿ-ವಿಭಾಗ',
    'sick_label': 'ಅನಾರೋಗ್ಯ',
    'on_leave_label': 'ರಜೆಯಲ್ಲಿ',
    'absent_label': 'ಗೈರುಹಾಜರು',
    'leave_requests_awaiting': 'ರಜೆ ವಿನಂತಿಗಳು ಅನುಮೋದನೆಗಾಗಿ ಕಾಯುತ್ತಿವೆ',
    'current_duty_card': 'ಪ್ರಸ್ತುತ ಕರ್ತವ್ಯ',
    'upcoming_schedule_card': 'ಮುಂಬರುವ ವೇಳಾಪಟ್ಟಿ',
    'leave_balance_card': 'ರಜೆ ಬಾಕಿ',
    'casual_leave_cl': 'ಸಾಂದರ್ಭಿಕ ರಜೆ (CL)',
    'earned_leave_el': 'ಗಳಿಕೆ ರಜೆ (EL)',
    'medical_cml': 'ವೈದ್ಯಕೀಯ (CML)',
    'next_scheduled_leave_label': 'ಮುಂದಿನ ನಿಗದಿತ ರಜೆ',
    'none_planned_label': 'ಯೋಜಿಸಲಾಗಿಲ್ಲ',
    'guard_i_duty': 'ಗಾರ್ಡ್-I ಕರ್ತವ್ಯ',
    'commissioner_office': 'ಆಯುಕ್ತರ ಕಚೇರಿ',
    'guard_ii_rotation': 'ಗಾರ್ಡ್-II ಸರದಿ',
    'next_cycle': 'ಮುಂದಿನ ಚಕ್ರ',
    'district_treasury': 'ಜಿಲ್ಲಾ ಖಜಾನೆ',
    'check_point_duty': 'ಚೆಕ್ ಪಾಯಿಂಟ್ ಕರ್ತವ್ಯ',
    'nh75_toll': 'NH-75 ಟೋಲ್',
    'striking_force_label': 'ಸ್ಟ್ರೈಕಿಂಗ್ ಫೋರ್ಸ್',
    'cc_room': 'CC ಕೊಠಡಿ',
    'shift_label': 'ಶಿಫ್ಟ್',
    'team_size': 'ತಂಡದ ಗಾತ್ರ',
    'personnel_unit': 'ಸಿಬ್ಬಂದಿ',
    // LeaveRequestsPage extras
    'casual_leave': 'ಸಾಂದರ್ಭಿಕ ರಜೆ',
    'medical_leave': 'ವೈದ್ಯಕೀಯ ರಜೆ',
    'earned_leave': 'ಗಳಿಕೆ ರಜೆ',
    'privilege_leave': 'ವಿಶೇಷ ರಜೆ',
    'casual_leave_full': 'ಸಾಂದರ್ಭಿಕ ರಜೆ',
    'medical_leave_full': 'ವೈದ್ಯಕೀಯ ರಜೆ',
    'earned_leave_full': 'ಗಳಿಕೆ ರಜೆ',
    'privilege_leave_full': 'ವಿಶೇಷ ರಜೆ',
    'of_days': '{0} ದಿನಗಳಲ್ಲಿ',
    'days_used_this_year': '{0} ದಿನಗಳು ಈ ವರ್ಷ ಬಳಸಲಾಗಿದೆ',
    'cancelled': 'ರದ್ದುಮಾಡಲಾಗಿದೆ',
    'all_count': 'ಎಲ್ಲಾ ({0})',
    'pending_count': 'ಬಾಕಿ ({0})',
    'approved_count': 'ಅನುಮೋದಿಸಲಾಗಿದೆ ({0})',
    'rejected_count': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ ({0})',
    // EmployeesPage extras
    'all_label': 'ಎಲ್ಲಾ',
    'all_ranks_label': 'ಎಲ್ಲಾ ಶ್ರೇಣಿಗಳು',
    'all_status_label': 'ಎಲ್ಲಾ ಸ್ಥಿತಿ',
    'leadership': 'ನಾಯಕತ್ವ',
    // DepartmentsPage extras
    'delete_confirm_msg': '"{0}" ಅನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ? ಈ ಕ್ರಿಯೆಯನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ.',
    // ShiftTypesPage
    'shift_types_title': 'ಶಿಫ್ಟ್ ವಿಧಗಳು',
    'configure_shift_defs': 'ಶಿಫ್ಟ್ ವ್ಯಾಖ್ಯಾನಗಳನ್ನು ಸಂರಚಿಸಿ',
    'add_shift_type': 'ಶಿಫ್ಟ್ ವಿಧ ಸೇರಿಸಿ',
    'edit_shift_type': 'ಶಿಫ್ಟ್ ವಿಧ ಸಂಪಾದಿಸಿ',
    'start_time': 'ಪ್ರಾರಂಭ ಸಮಯ',
    'end_time': 'ಅಂತಿಮ ಸಮಯ',
    'break_duration': 'ವಿರಾಮ ಅವಧಿ (ನಿಮಿಷಗಳು)',
    'break_label': 'ವಿರಾಮ',
    'category': 'ವರ್ಗ',
    'color': 'ಬಣ್ಣ',
    'regular': 'ನಿಯಮಿತ',
    'overtime': 'ಅಧಿಕ ಸಮಯ',
    'on_call': 'ಆನ್-ಕಾಲ್',
    'delete_shift_type': 'ಶಿಫ್ಟ್ ವಿಧ ಅಳಿಸಿ',
    'delete_confirm_shift': '"{0}" ಅನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?',
    // ShiftPatternsPage
    'shift_patterns_title': 'ಶಿಫ್ಟ್ ಮಾದರಿಗಳು',
    'configure_rotation_patterns': 'ಸರದಿ ಮಾದರಿಗಳನ್ನು ಸಂರಚಿಸಿ',
    'add_pattern': 'ಮಾದರಿ ಸೇರಿಸಿ',
    'edit_pattern': 'ಮಾದರಿ ಸಂಪಾದಿಸಿ',
    'cycle_days': 'ಚಕ್ರ (ದಿನಗಳು)',
    'rotation_cycle_days': 'ಸರದಿ ಚಕ್ರ (ದಿನಗಳು)',
    // RotationRulesPage
    'rotation_rules_title': 'ತಿರುಗುವಿಕೆ ನಿಯಮಗಳು',
    'manage_rotation_configs': 'ಕರ್ತವ್ಯ ಸರದಿ ಸಂರಚನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'add_rule': 'ನಿಯಮ ಸೇರಿಸಿ',
    'edit_rule': 'ನಿಯಮ ಸಂಪಾದಿಸಿ',
    'min_rest_hrs': 'ಕನಿಷ್ಠ ವಿಶ್ರಾಂತಿ (ಗಂ)',
    'max_consecutive_days': 'ಗರಿಷ್ಠ ಸತತ ದಿನಗಳು',
    'priority': 'ಆದ್ಯತೆ',
    'min_rest_hours': 'ಕನಿಷ್ಠ ವಿಶ್ರಾಂತಿ ಗಂಟೆಗಳು',
    // ShiftSchedulePage extras
    'leave_legend': 'ರಜೆ',
    // Pagination
    'no_records': 'ದಾಖಲೆಗಳಿಲ್ಲ',
    'rows': 'ಸಾಲುಗಳು:',
    // ShiftTypesPage extras
    'placeholder_shift_name': 'ಉದಾ., ಬೆಳಗಿನ ಶಿಫ್ಟ್',
    'placeholder_optional_desc': 'ಐಚ್ಛಿಕ ವಿವರಣೆ',
    'minutes_short': 'ನಿಮಿ',
    // ShiftPatternsPage extras
    'delete_pattern_confirm': 'ಈ ಮಾದರಿಯನ್ನು ಅಳಿಸಬೇಕೇ?',
    // RotationRulesPage extras
    'delete_rule_confirm': 'ಈ ನಿಯಮವನ್ನು ಅಳಿಸಬೇಕೇ?',
    'round_robin': 'ರೌಂಡ್ ರಾಬಿನ್',
    'skill_based': 'ಕೌಶಲ ಆಧಾರಿತ',
    'seniority_based': 'ಹಿರಿತನ ಆಧಾರಿತ',
    'preference_based': 'ಆದ್ಯತೆ ಆಧಾರಿತ',
    // LocationsPage extras
    'government_office': 'ಸರ್ಕಾರಿ ಕಚೇರಿ',
    'bank_currency_chest': 'ಬ್ಯಾಂಕ್ ಕರೆನ್ಸಿ ಚೆಸ್ಟ್',
    'court': 'ನ್ಯಾಯಾಲಯ',
    'hospital': 'ಆಸ್ಪತ್ರೆ',
    'ncc': 'NCC',
    'location_subtitle': 'ಮಂಗಳೂರು ನಗರ ವಿಭಾಗ — {0} ಸಕ್ರಿಯ {1} ಸ್ಥಳಗಳಲ್ಲಿ · {2} ಸಿಬ್ಬಂದಿ',
    'personnel_label_suffix': 'ಸಿಬ್ಬಂದಿ',
    // ProfilePage
    'profile_subtitle': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್, ರಜೆ ಬಾಕಿ ಮತ್ತು ಸೇವಾ ದಾಖಲೆಯನ್ನು ನೋಡಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ',
    'tab_overview': 'ಅವಲೋಕನ',
    'tab_leave_attendance': 'ರಜೆ ಮತ್ತು ಹಾಜರಾತಿ',
    'tab_service_record': 'ಸೇವಾ ದಾಖಲೆ',
    'tab_settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'contact_information': 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
    'achievements_awards': 'ಸಾಧನೆಗಳು ಮತ್ತು ಪ್ರಶಸ್ತಿಗಳು',
    'used_remaining': '{0} ಬಳಸಲಾಗಿದೆ · {1} ಉಳಿದಿದೆ',
    'my_pending_requests': 'ನನ್ನ ಬಾಕಿ ವಿನಂತಿಗಳು',
    'no_pending_leave': 'ಬಾಕಿ ರಜೆ ವಿನಂತಿಗಳಿಲ್ಲ',
    'holiday_calendar_2026': 'ರಜಾ ಕ್ಯಾಲೆಂಡರ್ 2026',
    'service_details': 'ಸೇವಾ ವಿವರಗಳು',
    'date_of_joining': 'ಸೇರಿದ ದಿನಾಂಕ',
    'current_rank': 'ಪ್ರಸ್ತುತ ಶ್ರೇಣಿ',
    'current_duty_profile': 'ಪ್ರಸ್ತುತ ಕರ್ತವ್ಯ',
    'unit': 'ಘಟಕ',
    'district': 'ಜಿಲ್ಲೆ',
    'years_of_service': 'ಸೇವಾ ವರ್ಷಗಳು',
    'awards_commendations': 'ಪ್ರಶಸ್ತಿಗಳು ಮತ್ತು ಶ್ಲಾಘನೆಗಳು',
    'training_history': 'ತರಬೇತಿ ಇತಿಹಾಸ',
    'account_settings': 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'sms_alerts': 'SMS ಎಚ್ಚರಿಕೆಗಳು',
    'sms_alerts_desc': 'ತುರ್ತು ಕರ್ತವ್ಯ ಬದಲಾವಣೆಗಳಿಗೆ SMS ಪಡೆಯಿರಿ',
    'email_notif_desc': 'ಕರ್ತವ್ಯ ಮತ್ತು ರಜೆ ಅಧಿಸೂಚನೆಗಳನ್ನು ಇಮೇಲ್ ಮೂಲಕ ಸ್ವೀಕರಿಸಿ',
    'language_pref_desc': 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    // HelpPage
    'find_answers': 'ಉತ್ತರಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ಸಹಾಯ ಪಡೆಯಿರಿ',
    'faq_title': 'ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು',
    'contact_support': 'ಬೆಂಬಲ ಸಂಪರ್ಕಿಸಿ',
    'quick_links': 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    'user_manual': 'ಬಳಕೆದಾರ ಕೈಪಿಡಿ',
    'video_tutorials': 'ವೀಡಿಯೊ ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು',
    'report_issue': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    'feature_request': 'ವೈಶಿಷ್ಟ್ಯ ವಿನಂತಿ',
    'faq_q1': 'ರಜೆ ಹೇಗೆ ವಿನಂತಿಸುವುದು?',
    'faq_a1': 'ಸೈಡ್‌ಬಾರ್‌ನಿಂದ ರಜೆ ವಿನಂತಿಗಳಿಗೆ ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿ, "ಹೊಸ ವಿನಂತಿ" ಕ್ಲಿಕ್ ಮಾಡಿ, ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ ಮತ್ತು ಸಲ್ಲಿಸಿ.',
    'faq_q2': 'ಸಹೋದ್ಯೋಗಿಯೊಂದಿಗೆ ಶಿಫ್ಟ್ ಬದಲಾಯಿಸುವುದು ಹೇಗೆ?',
    'faq_a2': 'ಸ್ವಾಪ್ ವಿನಂತಿಗಳಿಗೆ ಹೋಗಿ, ನೀವು ಬದಲಾಯಿಸಲು ಬಯಸುವ ಶಿಫ್ಟ್ ಮತ್ತು ಸಹೋದ್ಯೋಗಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ ಹೊಸ ಸ್ವಾಪ್ ವಿನಂತಿ ರಚಿಸಿ.',
    'faq_q3': 'ನನ್ನ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಹೇಗೆ ನೋಡುವುದು?',
    'faq_a3': 'ಕ್ಯಾಲೆಂಡರ್ ಅಥವಾ ಪಟ್ಟಿ ವೀಕ್ಷಣೆಯಲ್ಲಿ ನಿಮ್ಮ ನಿಯೋಜಿತ ಶಿಫ್ಟ್‌ಗಳನ್ನು ನೋಡಲು ಸೈಡ್‌ಬಾರ್‌ನಲ್ಲಿ ವೇಳಾಪಟ್ಟಿ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    'faq_q4': 'ನನ್ನ ರಜೆ ವಿನಂತಿಗಳನ್ನು ಯಾರು ಅನುಮೋದಿಸಬಹುದು?',
    'faq_a4': 'ನಿಮ್ಮ ವಿಭಾಗ ಶ್ರೇಣಿಯ ಆಧಾರದ ಮೇಲೆ ಮೇಲ್ವಿಚಾರಕರು ಮತ್ತು ನಿರ್ವಾಹಕರು ರಜೆ ವಿನಂತಿಗಳನ್ನು ಅನುಮೋದಿಸುತ್ತಾರೆ.',
    'faq_q5': 'ನನ್ನ ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿಯನ್ನು ಹೇಗೆ ನವೀಕರಿಸುವುದು?',
    'faq_a5': 'ಹೆಡರ್ ಡ್ರಾಪ್‌ಡೌನ್‌ನಿಂದ ನನ್ನ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೋಗಿ ಮತ್ತು ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ನವೀಕರಿಸಲು ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    // DocumentUploadPage
    'document_upload': 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್',
    'upload_parse_docs': 'ಕರ್ತವ್ಯ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ವಿಶ್ಲೇಷಿಸಿ',
    'upload_document': 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'upload_doc_desc': 'ನೀತಿ ದಾಖಲೆಗಳು, ವೇಳಾಪಟ್ಟಿಗಳು ಅಥವಾ ನಿಯಮ ಫೈಲ್‌ಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ಬೆಂಬಲಿತ ಸ್ವರೂಪಗಳು: PDF, DOCX, TXT, ಚಿತ್ರಗಳು.',
    'parsing_document': 'ದಾಖಲೆ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    'click_upload_drag': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ಡ್ರ್ಯಾಗ್ ಮತ್ತು ಡ್ರಾಪ್ ಮಾಡಿ',
    'file_types_hint': 'PDF, DOCX, TXT, ಅಥವಾ 10MB ವರೆಗಿನ ಚಿತ್ರಗಳು',
    'overall_confidence': 'ಒಟ್ಟಾರೆ ವಿಶ್ವಾಸ',
    'extracted_rules': 'ಹೊರತೆಗೆದ ನಿಯಮಗಳು',
    'upload_history': 'ಅಪ್‌ಲೋಡ್ ಇತಿಹಾಸ',
    'rules_extracted': '{0} ನಿಯಮಗಳನ್ನು ಹೊರತೆಗೆಯಲಾಗಿದೆ',
    'create_rotation_rules_btn': '{0} ತಿರುಗುವಿಕೆ ನಿಯಮ(ಗಳನ್ನು) ರಚಿಸಿ',
    // Sidebar extras
    'admin_section': 'ನಿರ್ವಾಹಕ',
    'expand': 'ವಿಸ್ತರಿಸಿ',
    'collapse_sidebar': 'ಕುಗ್ಗಿಸಿ',
    // LocationsPage CRUD
    'add_location_btn': 'ಸ್ಥಳ ಸೇರಿಸಿ',
    'edit_location': 'ಸ್ಥಳ ಸಂಪಾದಿಸಿ',
    'delete_location': 'ಸ್ಥಳ ಅಳಿಸಿ',
    'delete_location_confirm': '"{0}" ಅನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?',
    'location_name': 'ಸ್ಥಳದ ಹೆಸರು',
    'location_code': 'ಸ್ಥಳ ಕೋಡ್',
    'location_type': 'ಸ್ಥಳ ಪ್ರಕಾರ',
    'required_personnel_field': 'ಅಗತ್ಯ ಸಿಬ್ಬಂದಿ',
    'latitude': 'ಅಕ್ಷಾಂಶ',
    'longitude': 'ರೇಖಾಂಶ',
    'other': 'ಇತರೆ',
    'location_created': 'ಸ್ಥಳ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ',
    'location_updated': 'ಸ್ಥಳ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    'location_deleted': 'ಸ್ಥಳ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ',
    'all_locations': 'ಎಲ್ಲಾ ಸ್ಥಳಗಳು',
    'back_to_locations': 'ಸ್ಥಳಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    'configure_location_details': 'ಸ್ಥಳ ವಿವರಗಳು ಮತ್ತು ನಕ್ಷೆ ಸ್ಥಾನವನ್ನು ಸಂರಚಿಸಿ',
    'click_map_to_pick': 'ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ನಕ್ಷೆ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ',
    'click_map_pick': 'ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ನಕ್ಷೆ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ಮಾರ್ಕರ್ ಎಳೆಯಿರಿ',
    'map_preview': 'ನಕ್ಷೆ ಪೂರ್ವವೀಕ್ಷಣೆ',
    'preset_type': 'ಪೂರ್ವನಿಗದಿ',
    'custom_type': 'ಕಸ್ಟಮ್',
    'enter_custom_type': 'ಕಸ್ಟಮ್ ಸ್ಥಳ ಪ್ರಕಾರವನ್ನು ನಮೂದಿಸಿ...',
  }
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY)
    return (stored as Language) || 'en'
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}

export default LanguageContext
