import { createContext, useContext, useState, type ReactNode } from 'react'

type Language = 'en' | 'kn'

interface LanguageContextValue {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LANGUAGE_STORAGE_KEY = 'workboard_language'

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar
    'home': 'Home',
    'schedules': 'Schedules',
    'personnel': 'Personnel',
    'locations': 'Locations',
    'leave_requests': 'Leave Requests',
    'reports': 'Reports',
    'audit_log': 'Audit Log',
    'settings': 'Settings',
    'configuration': 'Configuration',
    'departments': 'Departments',
    'documents': 'Documents',
    'shift_types': 'Shift Types',
    'shift_patterns': 'Shift Patterns',
    'rotation_rules': 'Rotation Rules',
    // Header
    'my_profile': 'My Profile',
    'help_support': 'Help & Support',
    'sign_out': 'Sign Out',
    'notifications': 'Notifications',
    'dark_mode': 'Dark mode',
    'light_mode': 'Light mode',
    // HomePage
    'welcome_back': 'Welcome back',
    'here_is_what_is_happening': 'Here is what is happening today',
    'current_cycle': 'Current Cycle',
    'todays_assignments': "Today's Assignments",
    'recent_activity': 'Recent Activity',
    'ask_anything': 'Ask anything...',
    'assistant': 'Assistant',
    'listening': 'Listening...',
    'mock_data': 'Mock Data',
    'groq_connected': 'Connected',
    'groq_fallback': 'Groq fallback to mock',
    'llama_via_groq': 'Llama 3.3 via Groq',
    'attach_file': 'Attach file',
    // Suggestions
    'sug_schedule': "Show today's schedule",
    'sug_leave': 'Who is on leave today?',
    'sug_roster': 'Generate duty roster',
    'sug_pending': 'Pending leave requests',
    // Duty types
    'guard_i': 'Guard-I',
    'guard_ii': 'Guard-II',
    'check_point': 'Check Point',
    'prison_vip_escort': 'Prison/VIP Escort',
    'striking_force': 'Striking Force',
    // Common
    'search': 'Search',
    'actions': 'Actions',
    'status': 'Status',
    'name': 'Name',
    'date': 'Date',
    'type': 'Type',
    'department': 'Department',
    'role': 'Role',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'submit': 'Submit',
    'approve': 'Approve',
    'reject': 'Reject',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'active': 'Active',
    'inactive': 'Inactive',
    'loading': 'Loading...',
    'no_data': 'No data available',
    // Schedule page
    'schedule_title': 'Schedule Management',
    'shift_assignments': 'Shift Assignments',
    'create_assignment': 'Create Assignment',
    // Employees page
    'employees_title': 'Personnel Management',
    'add_employee': 'Add Employee',
    'employee_name': 'Employee Name',
    'employee_id': 'Employee ID',
    'phone': 'Phone',
    'email': 'Email',
    // Leave page
    'leave_title': 'Leave Requests',
    'request_leave': 'Request Leave',
    'leave_type': 'Leave Type',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'reason': 'Reason',
    'annual': 'Annual',
    'sick': 'Sick',
    'personal': 'Personal',
    // Locations page
    'locations_title': 'Locations Management',
    'add_location': 'Add Location',
    'city': 'City',
    'address': 'Address',
    // Reports page
    'reports_title': 'Reports & Analytics',
    'generate_report': 'Generate Report',
    // Audit page
    'audit_title': 'Audit Log',
    'action_type': 'Action Type',
    'performed_by': 'Performed By',
    'timestamp': 'Timestamp',
    // Settings page
    'settings_title': 'Settings',
    'general': 'General',
    'appearance': 'Appearance',
    'language': 'Language',
    // Schedule page extras
    'manage_duty_rotations': 'Manage duty rotations and assignments',
    'new_assignment': 'New Assignment',
    'active_platoons': 'Active Platoons',
    'total_personnel': 'Total Personnel',
    'platoon_assignments': 'Platoon Assignments',
    'platoon': 'Platoon',
    'current_duty': 'Current Duty',
    'view_details': 'View Details',
    'overview': 'Overview',
    'timeline': 'Timeline',
    'calendar': 'Calendar',
    'cycle': 'Cycle',
    // Employees page extras
    'manage_team': 'Manage your team members and their information',
    'add_personnel': 'Add Personnel',
    'on_leave': 'On Leave',
    'training': 'Training',
    'search_name_id': 'Search by name or ID...',
    'all_ranks': 'All Ranks',
    'all_status': 'All Status',
    'section': 'Section',
    'showing': 'Showing',
    'of': 'of',
    'previous': 'Previous',
    'next': 'Next',
    'view': 'View',
    'no_personnel_found': 'No personnel found',
    // Leave page extras
    'manage_leave': 'Manage leave applications and approvals',
    'request_leave_btn': 'Request Leave',
    'remaining': 'remaining',
    'days': 'days',
    'days_used': 'days used',
    'total_requests': 'Total Requests',
    'duration': 'Duration',
    'personnel_label': 'Personnel',
    'no_leave_requests': 'No leave requests found',
    'showing_requests': 'Showing',
    'requests': 'requests',
    // Locations page extras
    'guard_duty_locations': 'Guard Duty Locations',
    'manage_locations_subtitle': 'Manage 22 guard locations across Mangaluru',
    'total_locations': 'Total Locations',
    'personnel_required': 'Personnel Required',
    'location_types': 'Location Types',
    'search_name_code': 'Search by name or code...',
    'all_types': 'All Types',
    'show_inactive': 'Show Inactive',
    'required': 'required',
    'no_locations_found': 'No locations found matching your criteria',
    'locations_by_type': 'Locations by Type',
    // Reports page extras
    'reports_subtitle': 'Karnataka State Police CAR Unit reports',
    'strength_report': 'Strength Report',
    'rotation_status': 'Rotation Status',
    'leave_utilization': 'Leave Utilization',
    'guard_duty_coverage': 'Guard Duty Coverage',
    'total_present': 'Total Present',
    'sanctioned': 'Sanctioned',
    'vacancies': 'Vacancies',
    'sections': 'Sections',
    'personnel_by_section': 'Personnel by Section',
    'personnel_by_rank': 'Personnel by Rank',
    'rank': 'Rank',
    'present': 'Present',
    'vacancy': 'Vacancy',
    'current_rotation_cycle': 'Current 15-Day Rotation Cycle',
    'rotation_schedule_next': 'Rotation Schedule (Next 3 Cycles)',
    'leave_utilization_summary': 'Leave Utilization Summary',
    'by_leave_type': 'By Leave Type',
    'quick_stats': 'Quick Stats',
    'personnel_tracked': 'Personnel Tracked',
    'total_days_entitled': 'Total Days Entitled',
    'total_days_used': 'Total Days Used',
    'guard_locations': 'Guard Locations',
    'active_locations': 'Active Locations',
    'guard_location_details': 'Guard Location Details',
    'location': 'Location',
    'code': 'Code',
    // Audit page extras
    'audit_subtitle': 'Track all system activities and changes',
    'export_log': 'Export Log',
    'total_entries': 'Total Entries',
    'creates': 'Creates',
    'updates': 'Updates',
    'deletes': 'Deletes',
    'action': 'Action',
    'entity_type': 'Entity Type',
    'entity': 'Entity',
    'details': 'Details',
    'from': 'From',
    'to': 'To',
    'user_or_entity': 'User or entity...',
    'all_actions': 'All Actions',
    'no_audit_entries': 'No audit entries found',
    'page': 'Page',
    'audit_entry_details': 'Audit Entry Details',
    'time': 'Time',
    'user': 'User',
    'before': 'Before',
    'after': 'After',
    'close': 'Close',
    // Settings page extras
    'settings_subtitle': 'Manage your account and preferences',
    'profile': 'Profile',
    'dark_mode_label': 'Dark Mode',
    'dark_mode_desc': 'Toggle between light and dark theme',
    'email_notifications': 'Email Notifications',
    'email_notifications_desc': 'Receive notifications via email',
    'schedule_changes': 'Schedule Changes',
    'swap_requests': 'Swap Requests',
    'system_alerts': 'System Alerts',
    'voice_assistant': 'Voice Assistant',
    'enable_voice': 'Enable Voice Commands',
    'enable_voice_desc': 'Use voice to interact with the chatbot',
    'data_management': 'Data Management',
    'reset_data_desc': 'Reset all application data to default seed data. This is useful for demo purposes.',
    'reset_all_data': 'Reset All Data',
    'save_settings': 'Save Settings',
    'saved': 'Saved',
  },
  kn: {
    // Sidebar
    'home': 'ಮುಖಪುಟ',
    'schedules': 'ವೇಳಾಪಟ್ಟಿಗಳು',
    'personnel': 'ಸಿಬ್ಬಂದಿ',
    'locations': 'ಸ್ಥಳಗಳು',
    'leave_requests': 'ರಜೆ ವಿನಂತಿಗಳು',
    'reports': 'ವರದಿಗಳು',
    'audit_log': 'ಆಡಿಟ್ ಲಾಗ್',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'configuration': 'ಸಂರಚನೆ',
    'departments': 'ವಿಭಾಗಗಳು',
    'documents': 'ದಾಖಲೆಗಳು',
    'shift_types': 'ಶಿಫ್ಟ್ ವಿಧಗಳು',
    'shift_patterns': 'ಶಿಫ್ಟ್ ಮಾದರಿಗಳು',
    'rotation_rules': 'ತಿರುಗುವಿಕೆ ನಿಯಮಗಳು',
    // Header
    'my_profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    'sign_out': 'ಸೈನ್ ಔಟ್',
    'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'light_mode': 'ಲೈಟ್ ಮೋಡ್',
    // HomePage
    'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ',
    'here_is_what_is_happening': 'ಇಂದು ಏನಾಗುತ್ತಿದೆ ಎಂಬುದು ಇಲ್ಲಿದೆ',
    'current_cycle': 'ಪ್ರಸ್ತುತ ಚಕ್ರ',
    'todays_assignments': 'ಇಂದಿನ ನಿಯೋಜನೆಗಳು',
    'recent_activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    'ask_anything': 'ಏನಾದರೂ ಕೇಳಿ...',
    'assistant': 'ಸಹಾಯಕ',
    'listening': 'ಆಲಿಸುತ್ತಿದೆ...',
    'mock_data': 'ಮಾಕ್ ಡೇಟಾ',
    'groq_connected': 'ಸಂಪರ್ಕಿತ',
    'groq_fallback': 'Groq ಮಾಕ್‌ಗೆ ಫಾಲ್‌ಬ್ಯಾಕ್',
    'llama_via_groq': 'Llama 3.3 Groq ಮೂಲಕ',
    'attach_file': 'ಫೈಲ್ ಲಗತ್ತಿಸಿ',
    // Suggestions
    'sug_schedule': 'ಇಂದಿನ ವೇಳಾಪಟ್ಟಿ ತೋರಿಸಿ',
    'sug_leave': 'ಇಂದು ಯಾರು ರಜೆಯಲ್ಲಿದ್ದಾರೆ?',
    'sug_roster': 'ಕರ್ತವ್ಯ ರೋಸ್ಟರ್ ರಚಿಸಿ',
    'sug_pending': 'ಬಾಕಿ ರಜೆ ವಿನಂತಿಗಳು',
    // Duty types
    'guard_i': 'ಗಾರ್ಡ್-I',
    'guard_ii': 'ಗಾರ್ಡ್-II',
    'check_point': 'ಚೆಕ್ ಪಾಯಿಂಟ್',
    'prison_vip_escort': 'ಜೈಲು/ವಿಐಪಿ ಎಸ್ಕಾರ್ಟ್',
    'striking_force': 'ಸ್ಟ್ರೈಕಿಂಗ್ ಫೋರ್ಸ್',
    // Common
    'search': 'ಹುಡುಕಿ',
    'actions': 'ಕ್ರಿಯೆಗಳು',
    'status': 'ಸ್ಥಿತಿ',
    'name': 'ಹೆಸರು',
    'date': 'ದಿನಾಂಕ',
    'type': 'ಪ್ರಕಾರ',
    'department': 'ಇಲಾಖೆ',
    'role': 'ಪಾತ್ರ',
    'save': 'ಉಳಿಸಿ',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'delete': 'ಅಳಿಸಿ',
    'edit': 'ಸಂಪಾದಿಸಿ',
    'add': 'ಸೇರಿಸಿ',
    'submit': 'ಸಲ್ಲಿಸಿ',
    'approve': 'ಅನುಮೋದಿಸಿ',
    'reject': 'ತಿರಸ್ಕರಿಸಿ',
    'pending': 'ಬಾಕಿ',
    'approved': 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    'rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    'active': 'ಸಕ್ರಿಯ',
    'inactive': 'ನಿಷ್ಕ್ರಿಯ',
    'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'no_data': 'ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ',
    // Schedule page
    'schedule_title': 'ವೇಳಾಪಟ್ಟಿ ನಿರ್ವಹಣೆ',
    'shift_assignments': 'ಶಿಫ್ಟ್ ನಿಯೋಜನೆಗಳು',
    'create_assignment': 'ನಿಯೋಜನೆ ರಚಿಸಿ',
    // Employees page
    'employees_title': 'ಸಿಬ್ಬಂದಿ ನಿರ್ವಹಣೆ',
    'add_employee': 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ',
    'employee_name': 'ಸಿಬ್ಬಂದಿ ಹೆಸರು',
    'employee_id': 'ಸಿಬ್ಬಂದಿ ಐಡಿ',
    'phone': 'ಫೋನ್',
    'email': 'ಇಮೇಲ್',
    // Leave page
    'leave_title': 'ರಜೆ ವಿನಂತಿಗಳು',
    'request_leave': 'ರಜೆ ವಿನಂತಿಸಿ',
    'leave_type': 'ರಜೆ ಪ್ರಕಾರ',
    'start_date': 'ಪ್ರಾರಂಭ ದಿನಾಂಕ',
    'end_date': 'ಅಂತಿಮ ದಿನಾಂಕ',
    'reason': 'ಕಾರಣ',
    'annual': 'ವಾರ್ಷಿಕ',
    'sick': 'ಅನಾರೋಗ್ಯ',
    'personal': 'ವೈಯಕ್ತಿಕ',
    // Locations page
    'locations_title': 'ಸ್ಥಳಗಳ ನಿರ್ವಹಣೆ',
    'add_location': 'ಸ್ಥಳ ಸೇರಿಸಿ',
    'city': 'ನಗರ',
    'address': 'ವಿಳಾಸ',
    // Reports page
    'reports_title': 'ವರದಿಗಳು ಮತ್ತು ವಿಶ್ಲೇಷಣೆ',
    'generate_report': 'ವರದಿ ರಚಿಸಿ',
    // Audit page
    'audit_title': 'ಆಡಿಟ್ ಲಾಗ್',
    'action_type': 'ಕ್ರಿಯೆ ಪ್ರಕಾರ',
    'performed_by': 'ನಿರ್ವಹಿಸಿದವರು',
    'timestamp': 'ಸಮಯ ಮುದ್ರೆ',
    // Settings page
    'settings_title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'general': 'ಸಾಮಾನ್ಯ',
    'appearance': 'ನೋಟ',
    'language': 'ಭಾಷೆ',
    // Schedule page extras
    'manage_duty_rotations': 'ಕರ್ತವ್ಯ ಸರದಿಗಳು ಮತ್ತು ನಿಯೋಜನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'new_assignment': 'ಹೊಸ ನಿಯೋಜನೆ',
    'active_platoons': 'ಸಕ್ರಿಯ ಪ್ಲಟೂನ್‌ಗಳು',
    'total_personnel': 'ಒಟ್ಟು ಸಿಬ್ಬಂದಿ',
    'platoon_assignments': 'ಪ್ಲಟೂನ್ ನಿಯೋಜನೆಗಳು',
    'platoon': 'ಪ್ಲಟೂನ್',
    'current_duty': 'ಪ್ರಸ್ತುತ ಕರ್ತವ್ಯ',
    'view_details': 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    'overview': 'ಅವಲೋಕನ',
    'timeline': 'ಸಮಯರೇಖೆ',
    'calendar': 'ಕ್ಯಾಲೆಂಡರ್',
    'cycle': 'ಚಕ್ರ',
    // Employees page extras
    'manage_team': 'ನಿಮ್ಮ ತಂಡದ ಸದಸ್ಯರು ಮತ್ತು ಅವರ ಮಾಹಿತಿಯನ್ನು ನಿರ್ವಹಿಸಿ',
    'add_personnel': 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ',
    'on_leave': 'ರಜೆಯಲ್ಲಿ',
    'training': 'ತರಬೇತಿ',
    'search_name_id': 'ಹೆಸರು ಅಥವಾ ಐಡಿ ಮೂಲಕ ಹುಡುಕಿ...',
    'all_ranks': 'ಎಲ್ಲಾ ಶ್ರೇಣಿಗಳು',
    'all_status': 'ಎಲ್ಲಾ ಸ್ಥಿತಿ',
    'section': 'ವಿಭಾಗ',
    'showing': 'ತೋರಿಸುತ್ತಿದೆ',
    'of': 'ರಲ್ಲಿ',
    'previous': 'ಹಿಂದಿನ',
    'next': 'ಮುಂದಿನ',
    'view': 'ನೋಡಿ',
    'no_personnel_found': 'ಸಿಬ್ಬಂದಿ ಕಂಡುಬಂದಿಲ್ಲ',
    // Leave page extras
    'manage_leave': 'ರಜೆ ಅರ್ಜಿಗಳು ಮತ್ತು ಅನುಮೋದನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'request_leave_btn': 'ರಜೆ ವಿನಂತಿಸಿ',
    'remaining': 'ಉಳಿದಿದೆ',
    'days': 'ದಿನಗಳು',
    'days_used': 'ದಿನಗಳು ಬಳಸಲಾಗಿದೆ',
    'total_requests': 'ಒಟ್ಟು ವಿನಂತಿಗಳು',
    'duration': 'ಅವಧಿ',
    'personnel_label': 'ಸಿಬ್ಬಂದಿ',
    'no_leave_requests': 'ರಜೆ ವಿನಂತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'showing_requests': 'ತೋರಿಸುತ್ತಿದೆ',
    'requests': 'ವಿನಂತಿಗಳು',
    // Locations page extras
    'guard_duty_locations': 'ಕಾವಲು ಕರ್ತವ್ಯ ಸ್ಥಳಗಳು',
    'manage_locations_subtitle': 'ಮಂಗಳೂರಿನಾದ್ಯಂತ 22 ಕಾವಲು ಸ್ಥಳಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'total_locations': 'ಒಟ್ಟು ಸ್ಥಳಗಳು',
    'personnel_required': 'ಅಗತ್ಯ ಸಿಬ್ಬಂದಿ',
    'location_types': 'ಸ್ಥಳ ಪ್ರಕಾರಗಳು',
    'search_name_code': 'ಹೆಸರು ಅಥವಾ ಕೋಡ್ ಮೂಲಕ ಹುಡುಕಿ...',
    'all_types': 'ಎಲ್ಲಾ ಪ್ರಕಾರಗಳು',
    'show_inactive': 'ನಿಷ್ಕ್ರಿಯ ತೋರಿಸಿ',
    'required': 'ಅಗತ್ಯ',
    'no_locations_found': 'ನಿಮ್ಮ ಮಾನದಂಡಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುವ ಸ್ಥಳಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'locations_by_type': 'ಪ್ರಕಾರದ ಪ್ರಕಾರ ಸ್ಥಳಗಳು',
    // Reports page extras
    'reports_subtitle': 'ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್ CAR ಘಟಕ ವರದಿಗಳು',
    'strength_report': 'ಬಲ ವರದಿ',
    'rotation_status': 'ಸರದಿ ಸ್ಥಿತಿ',
    'leave_utilization': 'ರಜೆ ಬಳಕೆ',
    'guard_duty_coverage': 'ಕಾವಲು ಕರ್ತವ್ಯ ವ್ಯಾಪ್ತಿ',
    'total_present': 'ಒಟ್ಟು ಹಾಜರು',
    'sanctioned': 'ಮಂಜೂರಾದ',
    'vacancies': 'ಖಾಲಿ ಹುದ್ದೆಗಳು',
    'sections': 'ವಿಭಾಗಗಳು',
    'personnel_by_section': 'ವಿಭಾಗದ ಪ್ರಕಾರ ಸಿಬ್ಬಂದಿ',
    'personnel_by_rank': 'ಶ್ರೇಣಿಯ ಪ್ರಕಾರ ಸಿಬ್ಬಂದಿ',
    'rank': 'ಶ್ರೇಣಿ',
    'present': 'ಹಾಜರು',
    'vacancy': 'ಖಾಲಿ ಹುದ್ದೆ',
    'current_rotation_cycle': 'ಪ್ರಸ್ತುತ 15-ದಿನ ಸರದಿ ಚಕ್ರ',
    'rotation_schedule_next': 'ಸರದಿ ವೇಳಾಪಟ್ಟಿ (ಮುಂದಿನ 3 ಚಕ್ರಗಳು)',
    'leave_utilization_summary': 'ರಜೆ ಬಳಕೆ ಸಾರಾಂಶ',
    'by_leave_type': 'ರಜೆ ಪ್ರಕಾರದ ಪ್ರಕಾರ',
    'quick_stats': 'ತ್ವರಿತ ಅಂಕಿಅಂಶಗಳು',
    'personnel_tracked': 'ಟ್ರ್ಯಾಕ್ ಮಾಡಿದ ಸಿಬ್ಬಂದಿ',
    'total_days_entitled': 'ಒಟ್ಟು ಅರ್ಹ ದಿನಗಳು',
    'total_days_used': 'ಒಟ್ಟು ಬಳಸಿದ ದಿನಗಳು',
    'guard_locations': 'ಕಾವಲು ಸ್ಥಳಗಳು',
    'active_locations': 'ಸಕ್ರಿಯ ಸ್ಥಳಗಳು',
    'guard_location_details': 'ಕಾವಲು ಸ್ಥಳ ವಿವರಗಳು',
    'location': 'ಸ್ಥಳ',
    'code': 'ಕೋಡ್',
    // Audit page extras
    'audit_subtitle': 'ಎಲ್ಲಾ ಸಿಸ್ಟಮ್ ಚಟುವಟಿಕೆಗಳು ಮತ್ತು ಬದಲಾವಣೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'export_log': 'ಲಾಗ್ ರಫ್ತು ಮಾಡಿ',
    'total_entries': 'ಒಟ್ಟು ನಮೂದುಗಳು',
    'creates': 'ರಚನೆಗಳು',
    'updates': 'ನವೀಕರಣಗಳು',
    'deletes': 'ಅಳಿಸುವಿಕೆಗಳು',
    'action': 'ಕ್ರಿಯೆ',
    'entity_type': 'ಘಟಕ ಪ್ರಕಾರ',
    'entity': 'ಘಟಕ',
    'details': 'ವಿವರಗಳು',
    'from': 'ಇಂದ',
    'to': 'ವರೆಗೆ',
    'user_or_entity': 'ಬಳಕೆದಾರ ಅಥವಾ ಘಟಕ...',
    'all_actions': 'ಎಲ್ಲಾ ಕ್ರಿಯೆಗಳು',
    'no_audit_entries': 'ಆಡಿಟ್ ನಮೂದುಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'page': 'ಪುಟ',
    'audit_entry_details': 'ಆಡಿಟ್ ನಮೂದು ವಿವರಗಳು',
    'time': 'ಸಮಯ',
    'user': 'ಬಳಕೆದಾರ',
    'before': 'ಮೊದಲು',
    'after': 'ನಂತರ',
    'close': 'ಮುಚ್ಚಿ',
    // Settings page extras
    'settings_subtitle': 'ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'dark_mode_label': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'dark_mode_desc': 'ಲೈಟ್ ಮತ್ತು ಡಾರ್ಕ್ ಥೀಮ್ ನಡುವೆ ಬದಲಿಸಿ',
    'email_notifications': 'ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳು',
    'email_notifications_desc': 'ಇಮೇಲ್ ಮೂಲಕ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    'schedule_changes': 'ವೇಳಾಪಟ್ಟಿ ಬದಲಾವಣೆಗಳು',
    'swap_requests': 'ವಿನಿಮಯ ವಿನಂತಿಗಳು',
    'system_alerts': 'ಸಿಸ್ಟಮ್ ಎಚ್ಚರಿಕೆಗಳು',
    'voice_assistant': 'ಧ್ವನಿ ಸಹಾಯಕ',
    'enable_voice': 'ಧ್ವನಿ ಆಜ್ಞೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'enable_voice_desc': 'ಚಾಟ್‌ಬಾಟ್‌ನೊಂದಿಗೆ ಸಂವಹನ ನಡೆಸಲು ಧ್ವನಿ ಬಳಸಿ',
    'data_management': 'ಡೇಟಾ ನಿರ್ವಹಣೆ',
    'reset_data_desc': 'ಎಲ್ಲಾ ಅಪ್ಲಿಕೇಶನ್ ಡೇಟಾವನ್ನು ಡೀಫಾಲ್ಟ್ ಸೀಡ್ ಡೇಟಾಗೆ ಮರುಹೊಂದಿಸಿ. ಇದು ಡೆಮೊ ಉದ್ದೇಶಗಳಿಗೆ ಉಪಯುಕ್ತ.',
    'reset_all_data': 'ಎಲ್ಲಾ ಡೇಟಾ ಮರುಹೊಂದಿಸಿ',
    'save_settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ',
    'saved': 'ಉಳಿಸಲಾಗಿದೆ',
  }
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY)
    return (stored as Language) || 'en'
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}

export default LanguageContext
